INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GNURADIO_WAVELET gnuradio-wavelet)

FIND_PATH(
    GNURADIO_WAVELET_INCLUDE_DIRS
    NAMES gri_wavfile.h
    HINTS $ENV{GNURADIO_WAVELET_DIR}/include/gnuradio
        ${PC_GNURADIO_WAVELET_INCLUDEDIR}
    PATHS /usr/local/include/gnuradio
          /usr/include/gnuradio
)

FIND_LIBRARY(
    GNURADIO_WAVELET_LIBRARIES
    NAMES gnuradio-wavelet
    HINTS $ENV{GNURADIO_WAVELET_DIR}/lib
        ${PC_GNURADIO_WAVELET_LIBDIR}
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GNURADIO_WAVELET DEFAULT_MSG GNURADIO_WAVELET_LIBRARIES GNURADIO_WAVELET_INCLUDE_DIRS)
MARK_AS_ADVANCED(GNURADIO_WAVELET_LIBRARIES GNURADIO_WAVELET_INCLUDE_DIRS)
